name: SouiLeash
version: '3.1'
main: nc.SoulLeash
api-version: '1.21'
authors: [ WMGameLive ]
description: Allow to use lead on players!
commands:
  leashplayers:
    description: main command.
    usage: /<command> reload
    permission: leashplayers.admin
  oi:
    description: 看向主人
    usage: /oi
    permission: leashplayers.use
permissions:
  leashplayers.admin:
    description: admin permission.
    default: op
  leashplayers.use:
    description: allow leash other player.
    default: op
  leashplayers.leashable:
    description: allow to be leashed.
    default: not op

